export const SET_AUTH_DETAILS = "SET_AUTH_DETAILS";
export const CLEAR_AUTH_DETAILS = "CLEAR_AUTH_DETAILS";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const ADD_MARKER = "ADD_MARKER";
export const SET_MARKERS = "SET_MARKERS";
export const CLEAR_MARKERS = "CLEAR_MARKERS";
